import ai, { GEMINI_MODEL, DEEPSEEK_API_KEY, OPENAI_API_KEY } from "../config/ai.js";
import { buildCodeReviewPrompt } from "../utils/prompts.js";
import axios from 'axios';

const buildPrompt = (code, language) => {
    return `You are an expert senior software engineer.

Return ONLY valid JSON. The "suggestions" field must be an array of STRINGS only (not objects). 
The "bugs", "securityIssues", and "performanceIssues" fields must be arrays of objects with: severity, description, line, file.

The JSON must follow this structure exactly:

{
  "score": number,
  "categories": {
    "security": number,
    "performance": number,
    "quality": number,
    "maintainability": number,
    "readability": number,
    "bestPractices": number
  },
  "summary": "string",
  "bugs": [{"severity": "high/medium/low", "description": "string", "line": number, "file": "string"}],
  "securityIssues": [{"severity": "high/medium/low", "description": "string", "line": number, "file": "string"}],
  "performanceIssues": [{"severity": "high/medium/low", "description": "string", "line": number, "file": "string"}],
  "suggestions": ["string", "string"],
  "improvedCode": "string"
}

Review this code:

${buildCodeReviewPrompt(code, language)}`;
};

const sanitizeReview = (review) => {
    // Ensure suggestions is array of strings
    if (Array.isArray(review.suggestions)) {
        review.suggestions = review.suggestions.map(s => {
            if (typeof s === 'string') return s;
            if (typeof s === 'object' && s !== null) {
                return s.suggestion || s.message || s.description || JSON.stringify(s);
            }
            return String(s);
        });
    } else {
        review.suggestions = [];
    }

    // Ensure bugs is array of objects with correct structure
    if (Array.isArray(review.bugs)) {
        review.bugs = review.bugs.map(b => ({
            severity: b.severity || 'low',
            description: b.description || b.message || '',
            line: b.line || 0,
            file: b.file || ''
        }));
    } else {
        review.bugs = [];
    }

    // Ensure securityIssues is array of objects
    if (Array.isArray(review.securityIssues)) {
        review.securityIssues = review.securityIssues.map(s => ({
            severity: s.severity || 'low',
            description: s.description || s.message || '',
            line: s.line || 0,
            file: s.file || ''
        }));
    } else {
        review.securityIssues = [];
    }

    // Ensure performanceIssues is array of objects
    if (Array.isArray(review.performanceIssues)) {
        review.performanceIssues = review.performanceIssues.map(p => ({
            severity: p.severity || 'low',
            description: p.description || p.message || '',
            line: p.line || 0,
            file: p.file || ''
        }));
    } else {
        review.performanceIssues = [];
    }

    return review;
};

const generateLocalReview = (code, language) => {
    const lines = code.split('\n').length;
    const hasComments = code.includes('//') || code.includes('/*');
    const hasErrorHandling = code.includes('try') || code.includes('catch');
    
    let score = 75;
    if (hasComments) score += 5;
    if (hasErrorHandling) score += 5;
    score = Math.min(score, 95);
    
    const suggestions = [];
    if (!hasComments) suggestions.push("Add comments to explain complex logic");
    if (!hasErrorHandling) suggestions.push("Implement error handling with try-catch blocks");
    suggestions.push("Consider adding unit tests");
    
    console.log("Review generated by: Local Analysis");
    return {
        score,
        categories: {
            security: hasErrorHandling ? 82 : 72,
            performance: 80,
            quality: hasComments ? 85 : 78,
            maintainability: hasComments ? 83 : 75,
            readability: hasComments ? 88 : 80,
            bestPractices: hasErrorHandling ? 84 : 76
        },
        summary: `Analysis of ${language || 'code'}. Score: ${score}/100.`,
        bugs: [],
        securityIssues: [],
        performanceIssues: [],
        suggestions,
        improvedCode: code
    };
};

const parseJsonSafe = (text) => {
    if (!text) throw new Error("Empty AI response");
    let cleaned = text.trim();
    const jsonBlockMatch = cleaned.match(/```(?:json)?\s*([\s\S]*?)\s*```/);
    if (jsonBlockMatch) {
        cleaned = jsonBlockMatch[1].trim();
    }
    const firstBrace = cleaned.indexOf('{');
    const lastBrace = cleaned.lastIndexOf('}');
    if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
        cleaned = cleaned.substring(firstBrace, lastBrace + 1);
    }
    return JSON.parse(cleaned);
};

const reviewWithGemini = async (code, language) => {
    if (!ai) throw new Error("Gemini not configured");
    
    const fullPrompt = buildPrompt(code, language);
    
    const response = await ai.models.generateContent({
        model: GEMINI_MODEL,
        contents: fullPrompt,
    });
    
    const text = response.text || (response.candidates?.[0]?.content?.parts?.[0]?.text);
    if (!text) throw new Error("Empty response from Gemini");
    
    const parsed = parseJsonSafe(text);
    const sanitized = sanitizeReview(parsed);
    
    console.log("Review generated by: Gemini AI");
    return sanitized;
};

const reviewWithDeepSeek = async (code, language) => {
    if (!DEEPSEEK_API_KEY) throw new Error("DeepSeek not configured");
    
    const response = await axios.post(
        'https://api.deepseek.com/v1/chat/completions',
        {
            model: 'deepseek-chat',
            messages: [
                { role: 'system', content: 'You are an expert code reviewer. Respond with valid JSON only.' },
                { role: 'user', content: buildPrompt(code, language) }
            ],
            temperature: 0.3,
            max_tokens: 4000
        },
        {
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${DEEPSEEK_API_KEY}`
            },
            timeout: 30000
        }
    );
    
    const text = response.data.choices[0].message.content;
    const parsed = parseJsonSafe(text);
    const sanitized = sanitizeReview(parsed);
    console.log("Review generated by: DeepSeek AI");
    return sanitized;
};

const reviewWithOpenAI = async (code, language) => {
    if (!OPENAI_API_KEY) throw new Error("OpenAI not configured");
    
    const response = await axios.post(
        'https://api.openai.com/v1/chat/completions',
        {
            model: 'gpt-3.5-turbo',
            messages: [
                { role: 'system', content: 'You are an expert code reviewer. Respond with valid JSON only.' },
                { role: 'user', content: buildPrompt(code, language) }
            ],
            temperature: 0.3,
            max_tokens: 4000
        },
        {
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${OPENAI_API_KEY}`
            },
            timeout: 30000
        }
    );
    
    const text = response.data.choices[0].message.content;
    const parsed = parseJsonSafe(text);
    const sanitized = sanitizeReview(parsed);
    console.log("Review generated by: OpenAI (ChatGPT)");
    return sanitized;
};

export const reviewCode = async (code, language) => {
    // Try Gemini first 
    if (ai) {
        try {
            console.log("Attempting review with Gemini AI...");
            const result = await reviewWithGemini(code, language);
            return result;
        } catch (error) {
            console.log("Gemini failed:", error.message);
         
        }
    }
    
    // Try DeepSeek only if Gemini failed
    if (DEEPSEEK_API_KEY) {
        try {
            console.log("Attempting review with DeepSeek AI...");
            const result = await reviewWithDeepSeek(code, language);
            return result; 
        } catch (error) {
            console.log("DeepSeek failed:", error.message);
           
        }
    }
    
    // Try OpenAI only if both above failed
    if (OPENAI_API_KEY) {
        try {
            console.log("Attempting review with OpenAI...");
            const result = await reviewWithOpenAI(code, language);
            return result; 
        } catch (error) {
            console.log("OpenAI failed:", error.message);
            
        }
    }
    
    // Local fallback - only if ALL APIs failed
    console.log("All AI APIs failed. Generating local review...");
    return generateLocalReview(code, language);
};